// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsJLddgQGotWlM88sYvYl8MGg7h2p2y-8',
    appId: '1:17486368079:web:7aacb1679ad8852b37893a',
    messagingSenderId: '17486368079',
    projectId: 'messagesapp-98552',
    authDomain: 'messagesapp-98552.firebaseapp.com',
    storageBucket: 'messagesapp-98552.firebasestorage.app',
    measurementId: 'G-YT6560SRKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7pt91Vi-pua4AymVNM4Za-J13HH29tv4',
    appId: '1:17486368079:android:411e033fc845bc8b37893a',
    messagingSenderId: '17486368079',
    projectId: 'messagesapp-98552',
    storageBucket: 'messagesapp-98552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzib6ABkerYps8ZQMTsbHR9yzDAJx9Un0',
    appId: '1:17486368079:ios:3628923bf18dd6f637893a',
    messagingSenderId: '17486368079',
    projectId: 'messagesapp-98552',
    storageBucket: 'messagesapp-98552.firebasestorage.app',
    iosBundleId: 'com.example.meassagesapp',
  );
}
